<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{2a4304f3-537e-43d1-b89c-af5d9907262c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[CirculationPumpEx();
AntiBlockingPump();
Work();
Scheduler7ch();
Scheduler28ch();
SchedulerSpecialPeriods();
SchedulerPublicHolidays();
Motor1Speed();
Motor2Speed();
Motor3Speed();
TwoPointActuatorMode();
ThreePointActuatorMode();
TemperatureSensorEx2();
OverwriteAnalog();
AnalogInput();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="154" Count="0" />
      <LineId Id="289" Count="1" />
      <LineId Id="153" Count="0" />
      <LineId Id="187" Count="0" />
      <LineId Id="220" Count="0" />
      <LineId Id="253" Count="0" />
      <LineId Id="293" Count="2" />
      <LineId Id="298" Count="0" />
      <LineId Id="301" Count="0" />
      <LineId Id="304" Count="0" />
      <LineId Id="307" Count="0" />
      <LineId Id="310" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>